services:
  # Сервис PostgreSQL
  postgres:
    image: postgres:18
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: resale_market
      POSTGRES_USER: app_user1
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user1 -d resale_market"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис Spring Boot‑приложения
  app:
    build:
      context: .  # контекст — корень проекта
      dockerfile: Dockerfile  # путь к Dockerfile
    ports:
      - "8080:8080"  # приложение будет доступно на localhost:8080
    depends_on:
      - postgres  # ждём, пока запустится postgres
    restart: unless-stopped


volumes:
  postgres-data: